export const initialRoutingConfig = {
  parentPath: '',
  routePath: '/',
  element: '',
  props: [],
  index: false,
  caseSensitive: false,
  errorElement: '',
  loader: '',
  action: '',
  lazy: '',
};

export const availableRoutes = [
  { label: 'Select Route', value: '' },
  { label: '/', value: '1' },
  { label: '/about', value: '2' },
  { label: '/services', value: '3' },
  { label: '/services/design', value: '4' },
  { label: '/contact', value: '5' },
  { label: '/contact/add', value: '6' },
  { label: '/contact/edit', value: '7' },
];

export const availableElements = [
  { label: 'Select Component', value: '' },
  { label: 'Home', value: 'Home' },
  { label: 'About', value: 'About' },
  { label: 'Error404', value: 'Error404' },
  { label: 'Services', value: 'Services' },
  { label: 'Design', value: 'Design' },
  { label: 'Contact', value: 'Contact' },
  { label: 'Add Contact', value: 'AddContact' },
  { label: 'Edit Contact', value: 'EditContact' },

  // Add other elements here
];

export const routingTreeData = [
  {
    id: '1',
    parentPath: '',
    routePath: '/',
    element: 'Home',
    props: [],
    index: true,
    caseSensitive: false,
    errorElement: 'Error404',
    loader: 'fetchHomeData()',
    action: 'homeAction()',
    lazy: 'Home.lazy()',
    children: [],
  },
  {
    id: '2',
    parentPath: '',
    routePath: '/about',
    element: 'About',
    props: [
      { id: '1234', propName: 'prop1', propValue: 'qwerty' },
      { id: '54564', propName: 'prop33', propValue: 'qwerty' },
    ],
    index: false,
    caseSensitive: false,
    errorElement: 'Error404',
    loader: 'fetchAboutData()',
    action: 'aboutAction()',
    lazy: 'About.lazy()',
    children: [],
  },
  {
    id: '3',
    parentPath: '',
    routePath: '/services',
    element: 'Services',
    props: [],
    index: false,
    caseSensitive: false,
    errorElement: 'Error404',
    loader: 'fetchServicesData()',
    action: 'servicesAction()',
    lazy: 'Services.lazy()',
    children: ['4'],
  },
  {
    id: '4',
    parentPath: '3',
    routePath: '/design',
    element: 'Design',
    props: [
      { id: '1234', propName: 'prop1', propValue: 'qwerty' },
      { id: '54564', propName: 'prop33', propValue: 'qwerty' },
    ],
    index: false,
    caseSensitive: false,
    errorElement: 'Error404',
    loader: 'fetchDesignData()',
    action: 'designAction()',
    lazy: 'Design.lazy()',
    children: [],
  },
  {
    id: '5',
    parentPath: '',
    routePath: '/contact',
    element: 'Contact',
    props: [],
    index: false,
    caseSensitive: false,
    errorElement: 'Error404',
    loader: 'fetchContactData()',
    action: 'contactAction()',
    lazy: 'Contact.lazy()',
    children: ['6', '7'],
  },
  {
    id: '6',
    parentPath: '5',
    routePath: '/add',
    element: 'AddContact',
    props: [],
    index: false,
    caseSensitive: false,
    errorElement: 'Error404',
    loader: 'fetchContactData()',
    action: 'contactAction()',
    lazy: 'Contact.lazy()',
    children: [],
  },
  {
    id: '7',
    parentPath: '5',
    routePath: '/edit',
    element: 'EditContact',
    props: [],
    index: false,
    caseSensitive: false,
    errorElement: 'Error404',
    loader: 'fetchContactData()',
    action: 'contactAction()',
    lazy: 'Contact.lazy()',
    children: [],
  },
];

export const routerProviderData = { fallbackElement: '' };
