
import json
import subprocess
import os
from apps.common.utils.path_extractor import get_path_without_ext
import yaml

from apps.common.utils.file_helpers.dir_handler import create_parent_dir_if_not_exists, get_dir_path_from_file
from breeze_server.apps.common.constants.consts import NEW_LINE_CHAR
from apps.common.utils.formatter import format_val


PRIMARY_DATA_TYPE_INITIAL_VAL = {
    'integer' : 0,
    'number' : 0,
    'string' : '',
    'array' : [],
    'boolean' : 'false'
}

PRIMARY_DATA_TYPES = ['integer',
    'string' ,
    'array' ,
    'boolean']

class APIParametersMapping():
    app_config = None

    def __init__(self, app_config):
        self.app_config = app_config
        
    def initialize_data_type(self,init_state,key,obj,definition):
        
        if "type" in obj:
            if obj["type"] == 'object':
                init_state[key] = [self.generate_data_model(obj,definition)]
            
                
            elif obj["type"] == 'array':
                    items = obj["items"]
                    if 'type' in items:
                        init_state[key] = PRIMARY_DATA_TYPE_INITIAL_VAL[obj["type"]]
                    elif "$ref" in items:
                        ref = items["$ref"]
                        ref = ref.split("/")[-1]
                        init_state[key] = [self.generate_data_model(definition[ref],definition)]
            else:
                init_state[key] = PRIMARY_DATA_TYPE_INITIAL_VAL[obj["type"]]
        elif "$ref" in obj:
            ref = obj["$ref"]
            ref = ref.split("/")[-1]
            init_state[key] = self.initialize_data_type(init_state,ref,definition[ref],definition)
        else:
            pass
        return init_state

    def generate_data_model(self,obj,definition):
        properties = obj.get("properties",{})
        init_state = {}
        # get data type for initial value
        for property in properties:
            init_state =self.initialize_data_type(init_state,property,properties[property],definition)

        return init_state

            
    def generate_mapping_function(self,api_id,api_mappings):
        
        
        func_name = api_id.replace("-","_")
        parameters = api_mappings.get("parameters",{})
        mapping_schemas = api_mappings.get("schemas",{})
        mapping_obj = ""
        parameters_obj = {}
        func_args = []
        paris = []
        mapping_func_react_code = """
            const {FUNC_NAME} =  ({FUNC_ARGS}) => {
                let mappingObj = {MAPPING_OBJ};
                let parametersObj = {PARAMETER_OBJ};
                return {
                    'mappingObj' : mappingObj,
                    'parametersObj' : parametersObj
                };
            };
        """
        
        ## only for request body root schema
        ## any other nested schema will be generated by the recursive call
        ## prepare its mapping
        ref = 'AppConfigDetails'
        func_args.append('reactStateObj')
        mapping_obj = self.generate_schema_mapping(ref,mapping_schemas.get(ref,{}),mapping_schemas)    
            

        ## only for path and query parameters
        for key, parameter in parameters.items():
    
            if parameter.get("type") == "variable_mapping":
                value = parameter["value"]
                func_args.append(value)
                parameters_obj[key] = value
        
        parameters_obj = self.generate_parameter_mapping(parameters_obj)
  
        mapping_func_react_code = mapping_func_react_code.replace("{FUNC_NAME}",func_name)
        if len(func_args)>0:
            mapping_func_react_code = mapping_func_react_code.replace("{FUNC_ARGS}",",".join(func_args))
        else:
            mapping_func_react_code = mapping_func_react_code.replace("{FUNC_ARGS}","")
        
        mapping_func_react_code = mapping_func_react_code.replace("{PARAMETER_OBJ}",parameters_obj)
        mapping_func_react_code = mapping_func_react_code.replace("{MAPPING_OBJ}",mapping_obj)

        return mapping_func_react_code

    def generate_schema_mapping(self,key,mapping_schema,mapping_schemas):
        reactStateObj = ""
        body = {}
        self.map_object_properties(body,mapping_schema,mapping_schemas)
        reactStateObj =self.format_json_code_for_body(body)
        return reactStateObj

    def generate_parameter_mapping(self,parameter_obj):
        pairs = []
        for x,y in parameter_obj.items():
            pairs.append(" '%s' : %s"%(x,y))
        
        return "{"+",".join(pairs)+"}"
    
    def generate_code_for_required_params(self,parameter):
        code = ""
        if isinstance(parameter,str):
            code = """ if(!reactStateObj.hasOwnProperty('%s')){
                            validationErrors.push("%s is required")
                        }
                """%(parameter,parameter)
        else:
            name = parameter.get("name")
            code = """ if(%s == null || %s == ''){
                            validationErrors.push("%s is required")
                        }
                """%(name,name,name)
        return code

    def map_object_properties(self,body,obj,schemas):
        if obj.get("type") == "object_mapping":
            
            for key,property in obj.get("properties").items():
                mapping_value = ""
                value = obj.get("value",None)
                if value is None:
                    mapping_value = ""
                else:
                    mapping_value = f'{value}.'

                mapping_value = mapping_value+property.get("value",key)

                if property.get("type") == "variable_mapping":
                    body[key] = f'reactStateObj.{mapping_value}'
                
                elif property.get("type") == "array_object":
                    items = property.get("items")
                    if items.get("type") == "object_mapping":
                        ref = items.get("ref")    
                        body[key] = {}
                        self.map_object_properties(body[key],schemas.get(ref,{}),schemas)
                    
                    elif items.get("type") =="variable_mapping":
                        body[key] = f'reactStateObj.{mapping_value}'
                
                elif property.get("type") == "object_mapping":
                    ref = property.get("ref")    
                    body[key] = {}
                    self.map_object_properties(body[key],schemas.get(ref,{}),schemas)
        
        elif obj.get("type") == "array_mapping":
            pass  
                

    def format_json_code_for_body(self,body):
        pairs = []
        formatted_json = ""
        for i in body:
            if isinstance(body[i], dict):
                pairs.append(" '%s' : %s "%(i,self.format_json_code_for_body(body[i])))
            else:
                pairs.append(" '%s' : %s"%(i,body[i]))
        formatted_json ="{"+",".join(pairs)+"}"
        return formatted_json