const breezeConfigData = {
  'service-config': {
    id: 'service-config',
    name: 'api',
    extension: 'config',
    type: 'CONFIG',
    children: [],
    wasOpen: false,
    tag: 'SERVICE-CONFIG',
    parentId: null,
    isProtected: true,
  },
  'external-comp-config': {
    id: 'external-comp-config',
    name: 'external-comp',
    extension: 'config',
    type: 'CONFIG',
    children: [],
    wasOpen: false,
    tag: 'EXTERNAL_COMP',
    parentId: null,
    isProtected: true,
  },
  'schema-config': {
    id: 'schema-config',
    name: 'schema',
    extension: 'config',
    type: 'CONFIG',
    children: [],
    wasOpen: false,
    tag: 'SCHEMAS',
    parentId: null,
    isProtected: true,
  },
  'resource-config': {
    id: 'resource-config',
    name: 'resource',
    extension: 'config',
    type: 'CONFIG',
    children: [],
    wasOpen: false,
    tag: 'RESOURCE_CONFIG',
    parentId: null,
    isProtected: true,
  },
};

export default breezeConfigData;
