export const items = [
  'Add Import',
  'Variable',
  'Props',
  'Function',
  'Lifecycle',
  'Hook',
  'Html elements',
  'If Block',
  'While Block',
  'Do While Block',
  'Try Catch',
];
export const configTypeMapping = {
  ALL_IMPORTS: ['Edit Import', 'Add Import'],
  IMPORT: ['Edit Import', 'Add Import'],
  PROP: ['Edit Prop', 'Props'],
  REACT_COMPONENT: [
    'Variable',
    'Props',
    'Function',
    'Lifecycle',
    'Hook',
    'If Block',
    'While Block',
    'Do While Block',
    'Try Catch',
  ],
  RETURN_HTML_TREE: ['Html elements'],
  HTML_WRAP: ['Html elements'],
  HTML: ['Html elements'],
  IF_BLOCK: ['If Block', 'Edit If Block'],
  WHILE_BLOCK: ['While Block', 'Edit While Block'],
  DO_WHILE_BLOCK: ['Do While Block', 'Edit Do While'],
  BLOCK: ['If Block', 'While Block', 'Do While Block', 'Try Catch'],
  TRY_CATCH: ['Try Catch'],
};
